
services:
  web:
    container_name: tms-web
    image: tms-web:latest
    build:
      context: ../ 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    command: npm run dev